### ISSUE TITLE
Using parameters for HB analysis frequencies

### ISSUE THREAD

**Issue by eskiyerli** [Xyce/Xyce#13]
It is currently not possible to use parameters for HB analysis frequencies. It would be very useful to be able to parametrize HB analysis inputs.

**Comment by Karlsefni2012** [comment]
Thanks, that is a good point.  We will add this to our “to do” list.

**Comment by eskiyerli** [comment]
BTW, is there a way of reusing the initial condition files created as a result saveicdata option in HB analysis to help with the convergence?

**Comment by tvrusso** [comment]
For the record, this is a known issue and is documented in the "known defects" section of our reference guide under issue "932-SON", so it is already "on our to do list" but has not bubbled up to the top of team priorities and gotten fixed.
