### ISSUE TITLE
INSTALL file update

### ISSUE THREAD

**Issue by aolofsson** [Xyce/Xyce#3]
I think there needs to be directions add for running "bootstrap" before configure in INSTALL file, or remove the documentation if the correct compile method is elsewhere on website. WOuld be preferred for the repository would be self contained, without need to access a wiki.

Thanks!
Andreas

**Comment by tvrusso** [comment]
INSTALL is a generic file provided by Autoconf to document the "configure" script it creates.  It is not specific guidance for building Xyce.

We have just updated the text at the top of this file to make that clearer, and to direct users to the correct resource for Xyce-specific build instructions, which already have directions to run bootstrap.
