### ISSUE TITLE
Build Instructions/ Build Fails Arch Linux

### ISSUE THREAD

**Issue by metroid120** [Xyce/Xyce#48]
Dear Devs,

I just tried to build Xyce on the newest Arch Linux, the following things I found myself:
- using the newest c++ standard, the build fails. Please add the CPPFLAG -std=c++14 
(or whatever standard you prefer) to the documentation, then it works.
- add the "-j8" option on the documentation, helping your users build Xyce faster :)

When building Xyce, I get lots of linker errors in the end, like:

`/usr/bin/ld: ./.libs/libxyce.so: undefined reference to `Tpetra::MultiVector<double, int, long long, Kokkos::Compat::KokkosDeviceWrapperNode<Kokkos::Serial, Kokkos::HostSpace> >::description[abi:cxx11]() const'`

I suppose there is something wrong either with the current Trilinos, or Xyce build on my OS.
Find below my configure scripts, maybe you can help?

Thanks for your great work!

Trilinos:
```
#!/bin/sh
SRCDIR=/home/markus/Documents/Gitprojects/Trilinos
ARCHDIR=/home/markus/Documents/Gitprojects/Trilinos/XyceLibs/Serial
FLAGS="-O3 -fPIC -std=c++14"
cmake \
    -G "Unix Makefiles" \
    -DCMAKE_C_COMPILER=gcc \
    -DCMAKE_CXX_COMPILER=g++ \
    -DCMAKE_Fortran_COMPILER=gfortran \
    -DCMAKE_CXX_FLAGS="$FLAGS" \
    -DCMAKE_C_FLAGS="$FLAGS" \
    -DCMAKE_Fortran_FLAGS="$FLAGS" \
    -DCMAKE_INSTALL_PREFIX="$ARCHDIR" \
    -DCMAKE_MAKE_PROGRAM="make" \
    -DTrilinos_ENABLE_NOX=ON \
    -DNOX_ENABLE_LOCA=ON \
    -DTrilinos_ENABLE_EpetraExt=ON \
    -DEpetraExt_BUILD_BTF=ON \
    -DTpetra_INST_SERIAL:BOOL=ON \
    -DEpetraExt_BUILD_EXPERIMENTAL=ON \
    -DEpetraExt_BUILD_GRAPH_REORDERINGS=ON \
    -DTrilinos_ENABLE_TrilinosCouplings=ON \
    -DTrilinos_ENABLE_Ifpack=ON \
    -DTrilinos_ENABLE_AztecOO=ON \
    -DTrilinos_ENABLE_Belos=ON \
    -DTrilinos_ENABLE_Teuchos=ON \
    -DTeuchos_ENABLE_COMPLEX=ON \
    -DTrilinos_ENABLE_Amesos=ON \
    -DAmesos_ENABLE_KLU=ON \
    -DTrilinos_ENABLE_Amesos2=ON \
    -DAmesos2_ENABLE_KLU2=ON \
    -DAmesos2_ENABLE_Basker=ON \
    -DTrilinos_ENABLE_Sacado=ON \
    -DTrilinos_ENABLE_Stokhos=ON \
    -DTrilinos_ENABLE_Kokkos=ON \
    -DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES=OFF \
    -DTrilinos_ENABLE_CXX11=ON \
    -DTPL_ENABLE_AMD=ON \
    -DAMD_LIBRARY_DIRS="/usr/lib64" \
    -DTPL_AMD_INCLUDE_DIRS="/usr/include/suitesparse" \
    -DTPL_ENABLE_BLAS=ON \
    -DTPL_ENABLE_LAPACK=ON \
    $SRCDIR
```

Xyce:

```
/home/markus/Documents/Gitprojects/Xyce/configure \
    CXXFLAGS="-O3" \
    ARCHDIR="/home/markus/Documents/Gitprojects/Trilinos/XyceLibs/Serial" \
    CPPFLAGS="-I/usr/include/suitesparse -std=c++14" \
    F77=mpif77 \
    --enable-stokhos \
    --enable-xyce-shareable \
    --enable-shared \
    --enable-amesos2 \
    --prefix=$HOME/XyceInstall/Serial
```

**Comment by tvrusso** [comment]
Are you following our exact build guide instructions, which include a warning that Xyce should be built with Trilinos version 12.12.1 and not more recent versions from the git repo?

We have explicitly stated that at the moment, Xyce is not guaranteed to build against any recent version of trilinos, and often doesn't.

Our building guide tells you the correct options to use when you use Trilinos 12.12.1, where c++14 is not required.

If you want to download Trilinos from git, please switch to the branch "trilinos-release-12-12-branch", andyou will find that our instructions are correct for that version.
