### ISSUE TITLE
Xyce does not resolve parameters referencing other parameters on the same line

### ISSUE THREAD

**Issue by RTimothyEdwards** [Xyce/Xyce#60]
Other SPICE versions will resolve parameters which reference parameters that were defined earlier on the same line, as long as the parameter references are not circular.

For example, a MOSFET device instance created by xschem has estimated source and drain area and perimeter based on the device width and number of fingers:

```
XM10 out in VDD VDD sky130_fd_pr__pfet_g5v0d10v5 L=0.5 W=8 nf=2
+ ad='int((nf+1)/2) * W/nf * 0.29'
+ as='int((nf+2)/2) * W/nf * 0.29'
+ pd='2*int((nf+1)/2) * (W/nf + 0.29)'
+ ps='2*int((nf+2)/2) * (W/nf + 0.29)'
+ nrd='0.29 / W' nrs='0.29 / W'
+ sa=0 sb=0 sd=0 mult=1 m=1
```
These expressions should be valid because `W` and `nf` are defined before they are used.  However, with the above input, Xyce generates this error output:

```
Netlist error in file test_netlist.spice at or near line 10
 Parameter AD for device XM10 contains unrecognized symbols: NF W
Netlist error in file test_netlist.spice at or near line 10
 Parameter AS for device XM10 contains unrecognized symbols: NF W
Netlist error in file test_netlist.spice at or near line 10
 Parameter PD for device XM10 contains unrecognized symbols: NF W
Netlist error in file test_netlist.spice at or near line 10
 Parameter PS for device XM10 contains unrecognized symbols: NF W
Netlist error in file test_netlist.spice at or near line 10
 Parameter NRD for device XM10 contains unrecognized symbol: W
Netlist error in file test_netlist.spice at or near line 10
 Parameter NRS for device XM10 contains unrecognized symbol: W
Netlist error in file
```

This issue comes from a discussion on the skywater-pdk Slack workspace #xyce channel.  At the time there was a comment that it would be added to the Xyce github issue tracker.  Since I cannot find any reference to it here, I am adding the issue myself.  Eric Keiter is aware of the issue but it is still helpful to have the problem formally logged in the issue tracker.

**Comment by tvrusso** [comment]
This issue is already in our internal issue tracker and there is no need for one here.

Eric is already working this issue and it should be complete by the end of the month.

**Comment by RTimothyEdwards** [comment]
Can the issue be left open in the issue tracker until it is complete, so that people looking at the issue tracker will know that it is in progress?

**Comment by Karlsefni2012** [comment]
I don't mind re-opening it.   It is basically fixed in our internal git repository, so the fix will propagate to this repo the next time we do a merge.  So, it will probably just remain open for another week at most.

**Comment by RTimothyEdwards** [comment]
I guess it doesn't matter as long as I know the timeline and know that it is upcoming shortly.

**Comment by Karlsefni2012** [comment]
I might not have the "power" to reopen this myself.

**Comment by Karlsefni2012** [comment]
Reopening for now.  This should be closed pretty soon.
