### ISSUE TITLE
cmake buildsystem does not compile/expose XyceCInterface

### ISSUE THREAD

**Issue by olerichter** [Xyce/Xyce#65]
# Problem
When compiling Xyce with cmake, the N_CIR_XyceCInterface.c/.h  in utils/XyceCInerface dont get complied and installed,
as required for the Xyce integration in https://github.com/asyncvlsi/actsim

# workaround
when using autoconf install method they are included/build, but i assume you want to phase this build method out.

because the build method of actsim relies on some xyce's cmake build files to know what to statically link, i have to build xyce 2x (autobuild, cmake just conf) in the CI with the same options
# possible solution
I am sadly not fluent in setting up cmake systems otherwise i would have opened a pull request, migrating the XyceCInterface to the cmake build system.

**Comment by TBird2001** [comment]
There are several outstanding CMake capability issues, of which this is one. We are having a push right now to get the CMake builds up to the same level as the autotools builds. I'm not sure of the timeline for the fix, but we are working on it.

**Comment by olerichter** [comment]
now builds fine in the master branch with `cmake` and `make xycecinterface`, thanks a lot for all the effort!
