### ISSUE TITLE
Please consider naming release tarballs in a traditional way: xyce-{version}.tar.gz

### ISSUE THREAD

**Issue by yurivict** [Xyce/Xyce#80]
Current name is: https://github.com/Xyce/Xyce/archive/refs/tags/Release-7.5.0.tar.gz

This could simplify parts of port scrips that download tarballs.

**Comment by tvrusso** [comment]
The tarballs are named automatically by github using the release tag's name.

When downloaded through the github web interface directly they are all called "Xyce-Release-X.Y.Z.tar.gz" as desired.
