### ISSUE TITLE
In HB simulation, the phase of the source causes incorrect DC results.

### ISSUE THREAD

**Issue by allmybaby** [Xyce/Xyce#98]
As shown in the figure, for circuits with nonlinear devices, the phase of the source can lead to incorrect DC results.
In this example, when phase=90deg, the DC voltage is -0.082, but obviously the correct result should approach 0.
![f1](https://github.com/Xyce/Xyce/assets/42638476/a0968684-aad5-4df7-b0c0-72eae37b2b36)
![f2](https://github.com/Xyce/Xyce/assets/42638476/f42d0ba6-305d-42ff-b9ed-dea0f3ab524b)

netlist:
*
V1 1 0 SIN(0V 5 1G 0 0 90)
R1 1 0 R=50
B1 2 3 V={TANH(V(1))}
R2 3 0 R=50
.HB 1G
.OPTION HBINT NUMFREQ=3
.PRINT HB FORMAT=CSV V(2)

**Comment by tvrusso** [comment]
While there could possibly be a deeper issue involved here (and @hkthorn is the team expert on that), the problem can be made to go away by allowing HB to use many more frequencies than 3.

If you increase NUMFREQ, you will see that as the number of frequencies increases, the confusing DC component decreases.   When I tried 100 instead of 3, I found that both the 90 degree phase and 0 phase versions produce DC values down in the 1e-17 magnitude.   Using only 50 frequencies one gets something on the order of 1e-14 for the 90 degree phase and 1e-18 for the 0 phase.   This suggests that for this problem one can't get away with just a handful of frequencies.

Per the Xyce 7.8 users' guide:

![image](https://github.com/Xyce/Xyce/assets/10872812/044473af-70a0-4818-aa40-b9136b354285)

**Comment by tvrusso** [comment]
Indeed, if you run this circuit in transient and use ".fft v(2)" to print out the spectrum, there are significant components out to many harmonics (the magnitutes don't damp down to 1e-14 until out to something like the 93rd harmonic).   By doing HB with only 3 frequencies, you are likely getting a great deal of aliasing as HB startup involves performing a transient and then fourier transforming that to create an initial guess for the HB solution.

**Comment by tcaduser** [comment]
By definition, the imaginary component of the dc result has to be zero.   This can be enforced by the solver because it not even necessary to calculate the imaginary component at dc.

**Comment by tcaduser** [comment]
Could itr be something like this:
https://www.fftw.org/fftw3_doc/One_002dDimensional-DFTs-of-Real-Data.html

> Readers familiar with DFTs of real data will recall that the 0th (the “DC”) and n/2-th (the “Nyquist” frequency, when n is even) elements of the complex output are purely real. Some implementations therefore store the Nyquist element where the DC imaginary part would go, in order to make the input and output arrays the same size. Such packing, however, does not generalize well to multi-dimensional transforms, and the space savings are miniscule in any case; FFTW does not support it.

**Comment by tcaduser** [comment]
This looks like an interesting problem to me.  When sampling at the nyquist frequency, the imaginary component of the solution is lost.  Perhaps by shifting the phase of the source, what was the imaginary component is now real, being sampled, and has affected the dc result.

**Comment by allmybaby** [comment]
In fact, it is not just the DC results that are affected. All even harmonics (such as 2GHz, 4GHz) exhibit significant amplitude. The results at all even harmonics (such as 2GHz, 4GHz) are also incorrect. In theory， the Taylor expansion of tanh only has odd order terms, and the Fourier series of rectangular waves should only have odd order harmonics.

**Comment by tcaduser** [comment]
My python interpretation of the circuit is this:
```
import numpy
import math
H = 3
N = 2*H-1
V=5
points = 2*math.pi * (numpy.linspace(0, N, num=N, endpoint=False)/N)
# sin
print(numpy.average(numpy.tanh(V*numpy.sin(points)))/2)
# sin offset by 90
print(numpy.average(numpy.tanh(V*numpy.sin(points + math.pi/2)))/2)
```

with this result:

sin
```
1.1102230246251566e-17
```

sin offset by 90
```
0.08270767344697012
```

So I think it really depends on the number of harmonics and how the source is being sampled.  Node 2 is floating, so I am assuming that no current is flowing through the termination resistor at node 3.

**Comment by allmybaby** [comment]
I think what you said makes sense. By the way, node 2 float is an error. There should also be a resistor grounded from node 2. But this will not affect the observation of the problem.
But it seems insufficient to explain the occurrence of even harmonics.

**Comment by tvrusso** [comment]
As I said, using a grossly insufficient number of frequencies in HB analysis will give you junk answers, and you're seeing that.  Trying to make sense out of the results before determining whether you've got enough is wasting your time.  It would be like doing finite element analysis without doing a mesh convergence study and trying to draw conclusions from the results.

With 3 frequencies, you're getting all manner of aliasing junk.

As per the guidance on using HB, you must increase the number of frequencies until the answer stops changing significantly.  Do that and the nonsense results go away.

With 100 frequencies, you will find that only odd frequencies have substantial value.

Just looking at the lowest harmonics of the 100 frequency problem with 90 degree input phase:


```
Index       FREQ            Re(V(2))          Im(V(2))     
...
89      -1.10000000e+10   -1.27476723e-02   -4.88927261e-17
90      -1.00000000e+10    2.19665543e-17    1.89415632e-18
91      -9.00000000e+09    2.37615204e-02    4.54160060e-17
92      -8.00000000e+09   -2.14614175e-17    1.95071063e-18
93      -7.00000000e+09   -4.46691988e-02   -5.96007033e-17
94      -6.00000000e+09    4.21521198e-17   -1.75123127e-18
95      -5.00000000e+09    8.62406740e-02    1.02210377e-16
96      -4.00000000e+09   -7.79651144e-17   -1.27401504e-17
97      -3.00000000e+09   -1.82787470e-01   -1.35115927e-16
98      -2.00000000e+09    1.63890122e-17   -5.68287024e-18
99      -1.00000000e+09    6.25698786e-01    1.55587929e-16
100      0.00000000e+00   -4.49749067e-17    0.00000000e+00
101      1.00000000e+09    6.25698786e-01   -1.55587929e-16
102      2.00000000e+09    1.63890122e-17    5.68287024e-18
103      3.00000000e+09   -1.82787470e-01    1.35115927e-16
104      4.00000000e+09   -7.79651144e-17    1.27401504e-17
105      5.00000000e+09    8.62406740e-02   -1.02210377e-16
106      6.00000000e+09    4.21521198e-17    1.75123127e-18
107      7.00000000e+09   -4.46691988e-02    5.96007033e-17
108      8.00000000e+09   -2.14614175e-17   -1.95071063e-18
109      9.00000000e+09    2.37615204e-02   -4.54160060e-17
110      1.00000000e+10    2.19665543e-17   -1.89415632e-18
111      1.10000000e+10   -1.27476723e-02    4.88927261e-17
```

Note that the DC value is essentially zero, as are all the even harmonics.

**Comment by tcaduser** [comment]
> I think what you said makes sense. By the way, node 2 float is an error. There should also be a resistor grounded from node 2. But this will not affect the observation of the problem. But it seems insufficient to explain the occurrence of even harmonics.

Again, it is a sampling problem.  If I print out the fft results of my python circuit:
```
import numpy
import math
import scipy
H = 4
N = 2*H-1
V=5
points = 2*math.pi * (numpy.linspace(0.0, 1.0, num=N, endpoint=False))
# sin
print(numpy.average(numpy.tanh(V*numpy.sin(points)))/2)
# sin offset by 90
print(numpy.average(numpy.tanh(V*numpy.sin(points + math.pi/2)))/2)

s1 = numpy.tanh(V*numpy.sin(points))
s2 = numpy.tanh(V*numpy.sin(points + math.pi/2))
print(scipy.fft.rfft(s1))
print(scipy.fft.rfft(s2))
```

you will see that the even order harmonics appear with the undersampling and the phase shift of the source:
```
-0.04409916465560003
[ 1.11022302e-16+0.j
-1.00027638e-16-4.35744133j
  6.92212734e-17+0.44275057j
 -2.47047864e-17-1.20320275j]

[-0.61738831+0.00000000e+00j
4.40175828-2.05653609e-15j
  0.76045946+9.15244663e-16j
 -1.35384138+1.64921390e-15j]
```

**Comment by tvrusso** [comment]
And even in this simple python program, you can see that increasing the number of samples and number of harmonics corrects the issue.  Try it with H=100 and poof, the spectrum starts to look more like the theoretical expansion, irrespective of input phase.

It all comes back to making sure you're using the tool correctly.   HB in its basic usage in Xyce starts with a transient simulation and fourier transforms that to get an initial guess at the HB solution.   Except in the rare cases of devices that have been written to work directly in frequency domain (such as the independent sources and the lossless and lossy transmission lines), Xyce must at each step of the HB solution must obtain each device's contribution by transforming the current solution back into the time domain and evaluating the devices in that domain, then Fourier transforming back.

Xyce's output in the ".HB.TD" output file is nothing more than the reverse Fourier transform of the final (I hesitate to say "converged") HB solution.  If you look at that solution when there are only 3 frequencies in the HB analysis, it looks nothing like what it would if you simulated it in the time domain in the first place.

You can't expect the HB result to look like the theoretical infinite Fourier expansion of the expected solution if you've truncated the expansion to such a drastic degree that the behaviors of the signals can't be captured in the frequency domain.
